### ISSUE TITLE
Awesome tech! But how does it all work?

### ISSUE THREAD

**Issue by markg85** [ceramicnetwork/js-did#20]
Hi,

The title might be super broad but it's the first thing that comes to my mind when reading this awesome article [(How to store signed and encrypted data on IPFS)](https://blog.ceramic.network/how-to-store-signed-and-encrypted-data-on-ipfs/).

But now i'm really confused as to how everything works together and how i can use it as a developer.
First, i'll explain what my usecase is to give you an idea of what problem i'm trying to solve.

In a very general way i want my website to be able to use the IPFS pubsub mechanism. That makes it possible for my site to receive messages from any IPFS client and likewise for the site to send messages back to the IPFS pubsub network. I have this working by basically making a websocket proxy on top of the IPFS API. This does give the website a single point of entry (and thus failure) but it seemed to be the most reliable way of doing this. Other projects do exist that use [libp2p-webrtc-star](https://github.com/libp2p/js-libp2p-webrtc-star) but they turned out to be unusable in my case. You can find a discussion thread about that [here](https://discuss.ipfs.io/t/use-ipfs-pubsub-in-a-website/9455).

But, and this is where my interest from the first link in this post comes in, I need some mechanism to authenticate a message from a website on an IPFS node and vice versa. I was about to craft something up like JWS till i found that article that changed my idea of how to tackle this. In my idea both the website and the IPFS node should have a means to identify and verify a message on the pubsub channel. A DID where both parties have a list of "trusted DID's" would seem quite fancy and awesome in my opinion! And yes, this does mean that the node running IPFS will have a second application running (listening on a specific pubsub channel) to handle the messages. It is very much a client-server model. The main advantage is that it's very easy to spin up that "server" on some other node where IPFS is also running. The website itself is not backed by a server, it's running fully client side! 

But here is where i'm getting stuck in the slew of different terms and technologies where it's totally not clear to me how i should be using them.

I "think" i need to be using a **DID provider**? But:

1. How do i "register" a DID?
2. Is this on the blockchain or on IPFS? [1]
3. If it's the blockchain, how do i pay? Do i even need to pay? How do i get a DID on there?
4. Can i use DID's without a blockchain, like directly on IPFS? If so, how?
5. Can i do this without the need for a "web3" browser addon like metamask? [2]
6. What is [js-ipfs-did-document](https://github.com/3box/js-ipfs-did-document)? Should i be using that for the above case? It seems to be developed by the same people as the Ceramic Network hence asking here doesn't seem unreasonable.
7. Ceramic, 3ID, 3BOX... How does it all tie together?
8. is 3ID the same as DID?

@oed seems to be involved in much or all of this :)

[1] How can a DID be on IPFS? If you change your public key (or change anything in your DID really), doesn't the DID change too? As well, IPFS is immutable... Thus any change is a new CID (yes, **C**ID), i'm not sure how **D**ID is handling mutations.
[2] I want to use the IPFS pubsub network on a site. On mobile too. If i need to have a browser addon then this isn't going to work out for me.

Sorry for all the questions here. I'm trying to understand how it all ties together and how i can make use of it in my case.

Cheers,
Mark

**Comment by oed** [comment]
Hey! It sounds like the easiest way for you to get started would be to use this package: https://github.com/ceramicnetwork/key-did-provider-ed25519 It is a DID provider where you simply provide a `seed` (32 bytes of entropy) and get a DID. The `seed` is private and each user needs to have their own. This DID never touches any blockchain or IPFS. The only thing you need to pass around is the did string itself (`did:key:z...`). You should be able to see how you use it in the readme. 

I think the above hint should allow you to get going, but I'll also address your specific questions:

1. Depends on which DID method you're using. The library I linked above is the simplest way of doing it.
2. It can be both, or neither :)
3. Depends on which DID method you're using.
4. See library above!
5. Yep, see lib above
6. This is an old library that is not actively maintained.
7. Ceramic is a decentralized network for mutable documents. 3ID is a DID method that is built on top of Ceramic. 3Box Labs is the company building this tech (3box-js is our previous product).
8. 3ID is a specific DID method. There are many different DID methods.

Hope this helps! Let me know if you have other questions as you're building :)

**Comment by markg85** [comment]
Sorry for the very late response (regarding https://github.com/ceramicnetwork/js-did/issues/20)! Thank you very much for your reply! I'll definitely have to play with https://github.com/ceramicnetwork/key-did-provider-ed25519 to see if it fits my needs. But based on what you said and what i'm reading, it's looking good! Code time i to play with it i suppose :smile:

Closing this one as you basically answered everything.
