### ISSUE TITLE
Attach capabilities to a DID instance

### ISSUE THREAD

**Issue by haardikk21** [ceramicnetwork/js-did#50]
# Description

We add a method withCapability(cacao) to DID instance. It returns a one-off DID instance, that for the invocations of createJWS or createDagJWS attaches a reference to the passed cacao in a jws header. Namely, it adds `cap` header with reference to the cacao parameter in form ipfs://<cacao-cid>.

# Technical Information

Needs cacao package to be on npm

**Comment by oed** [comment]
Possibly also add an optional param in the constructor.
