### ISSUE TITLE
[error on self.id authenticate]  did_jwt_1.verifyJWS is not a function

### ISSUE THREAD

**Issue by sunz7** [ceramicnetwork/js-did#61]
# Description
hi team, I keep getting an error in the console when trying to authenticate 

```
did.js:209 Uncaught (in promise) TypeError: did_jwt_1.verifyJWS is not a function
    at DID.<anonymous> (did.js:209:1)
    at Generator.next (<anonymous>)
    at fulfilled (did.js:13:1)
```

here is my code, just copied from the [docs](https://developers.ceramic.network/tools/self-id/write/)
```
    const addresses = await window.ethereum.request({
      method: 'eth_requestAccounts'
    })

    // The following configuration assumes your local node is connected to the Clay testnet
    const self = await SelfID.authenticate({
      authProvider: new EthereumAuthProvider(window.ethereum, addresses[0]),
      ceramic: 'https://ceramic-clay.3boxlabs.com',
      connectNetwork: 'testnet-clay'
    })
```

# Technical Information

versions
```
    "@self.id/web": "^0.2.0",
    "did-jwt": "^5.12.3", // do I need this?
    "dids": "^2.3.3",
```
![Screen Shot 2022-01-18 at 2 09 11 PM](https://user-images.githubusercontent.com/6427843/149880485-8cf09567-1822-422a-b7e0-f8c6200213c0.png)

anything I did wrong? thanks

**Comment by sunz7** [comment]
change version to following seems to fix it
"did-jwt": "5.12.1",

**Comment by stbrody** [comment]
glad you were able to figure it out!  Please let us know if you have further issues
