### ISSUE TITLE
createDagJWE returning an error

### ISSUE THREAD

**Issue by alexkeating** [ceramicnetwork/js-did#63]
# Description

I am trying to encrypt some text with createDagJWE and get the below error.

# Technical Information

I am getting the below error when trying to use createDagJWE on a DID object.
```
TypeError: Cannot read properties of undefined (reading 'alg')
    at Object.createJWE (JWE.ts:98:21)
    at DID.<anonymous> (did.ts:283:12)
    at Generator.next (<anonymous>)
    at fulfilled (utils.ts:51:1)
```

It seems like the underlying did module it is trying to access has a different path than it expects. So, in did.ts I see Could not load content for http://localhost:3000/node_modules/dids/src/did.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE), but the actual path in my node modules is dids/lib/did.js. Any ideas how I can resolve this?

**Comment by ukstv** [comment]
@alexkeating Please, could you provide more details on how exactly you call `createDagJWE`? What arguments do you pass there? If you are doing it in browser context, please, also state what bundler you are using (CRA v4, CRA v5, Next.js,...) and what version of packages are you on.

**Comment by alexkeating** [comment]
Yes, definitely, let me know if this is enough detail

Bundler: Vite
Version dids: 2.4.3

Function call
```
const getIPFSClient = () => {
  const auth =
    "Basic " +
    Buffer.from(
      import.meta.env.REACT_APP_INFURA_PROJECT_ID +
        ":" +
        import.meta.env.REACT_APP_INFURA_PROJECT_SECRET
    ).toString("base64");
  const ipfs = create({
    host: "ipfs.infura.io",
    port: 5001,
    protocol: "https",
    headers: {
      authorization: auth,
    },
  });
  return ipfs;
};

export const encryptText = async (
  did: DID,
  text: string,
  sharedDids: string[]
) => {
  const jwe = await did.createDagJWE({ text }, sharedDids || [did.id]); // Errors on this line
  const ipfs = getIPFSClient();

  // put the JWE into the ipfs dag
  // Add ipfs
  const jweCid = await ipfs.dag.put(jwe, {
    storeCodec: "dag-jose",
    hashAlg: "sha2-256",
  });

  return jweCid;
};
```
